version: '3'
services:
  nest: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3025:3025"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=d77edc8800ef11eebe560242ac120002
      - POSTGRES_DB=icarus-db
  redis:
    image: redis:latest
    ports:
      - 6379:6379